### ISSUE TITLE
ХААХХАХАХАХААХХАХА

### ISSUE THREAD

**Issue by ghost** [LORD-ME-CODE/barley#2]
че у тебя за говнокод в бд

**Comment by lrdcxdes** [comment]
> че у тебя за говнокод в бд 

Не знаю, сам бот говнокод

**Comment by ghost** [comment]
> > че у тебя за говнокод в бд
> 
> Не знаю, сам бот говнокод

я ожидал услышать в ответ все что угодно но не это
